name: Claude Code Action

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  claude:
    if: |
      contains(github.event.comment.body, '@claude') ||
      contains(github.event.issue.body, '@claude') ||
      contains(github.event.review.body, '@claude')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Debug Event Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "Review body: ${{ github.event.review.body }}"
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Claude Code Action
        uses: anthropics/claude-code-action@v0.0.7
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: 25
          custom_instructions: "日本語で応答してください。セキュリティとベストプラクティスを重視してください。" 